### ISSUE TITLE
Plugin is not getting added

### ISSUE THREAD

**Issue by jasvindersingh-evon** [iampossible/Cordova-DocPicker#1]
ionic cordova plugin add cordova-plugin-documentpicker
> cordova plugin add cordova-plugin-documentpicker --save
(node:32975) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not found : cordova-plugin-documentpicker
npm ERR! 404
npm ERR! 404  'cordova-plugin-documentpicker' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by AmadeuReal** [comment]
Hello, try instead : `cordova plugin add https://github.com/iampossible/Cordova-DocPicker.git`
