### ISSUE TITLE
Unable to build iOS via phonegap: Check dependencies, SWIFT_VERSION

### ISSUE THREAD

**Issue by alexverbitsky** [iampossible/Cordova-DocPicker#12]
Getting following error from Phonegap: 

_Check dependencies_
_The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor._
_The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor._

_** ARCHIVE FAILED **_

_The following build commands failed:_
	_Check dependencies_
_(1 failure)_
_Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,project.xcworkspace,-scheme,project,-configuration,Release,-destination,generic/platform=iOS,-archivePath,project.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch,-UseModernBuildSystem=0_

**Dependencies at package.json**: 
"ionic-angular": "3.8.0",
"@ionic-native/document-picker": "4.20.0",
"cordova-ios": "4.5.5",
"cordova-documentpicker": "git+https://github.com/iampossible/Cordova-DocPicker.git#a306b36c9037d28485829702c4476ccdc607860c",
"cordova-plugin-add-swift-support": "2.0.2",

**Config.xml**:

`<platform name="ios">`
    `   <preference name="UseSwiftLanguageVersion" value="4.2" />`
  `</platform>`

   `<plugin name="cordova-plugin-add-swift-support" spec="2.0.2" />`
   `<plugin`
      `   name="cordova-documentpicker"`
      `   source="git"`
      `   spec="https://github.com/iampossible/Cordova-DocPicker.git#a306b36c9037d28485829702c4476ccdc607860c"`
   `/>`

Also I tried to use `<preference name="UseLegacySwiftLanguageVersion" value="true" />` as discribed at cordova-plugin-add-swift-support docs, and the other values for UseSwiftLanguageVersion.

Phonegap build update worked without any issue on 25th of May when I added cordova-documentpicker the first time

**Comment by alexverbitsky** [comment]
Can't fix is described here
https://github.com/iampossible/Cordova-DocPicker/issues/5

**Comment by alexverbitsky** [comment]
Seems like the plugin has been written on Swift 2 or lower. 
cordova-plugin-add-swift-support doesn't resolve the issue.
Also migration to 3.x at least is impossible without downgrading to High Sierra and installing xcode 8.x
Be careful when use this plugin, wasted a lot of time on investigation.

**Comment by AmadeuReal** [comment]
I'm so sorry for only getting to you right now… But this issue is mitigated.
