### ISSUE TITLE
Slow to open on first run - UI API called on a background thread

### ISSUE THREAD

**Issue by AndrWeisR** [iampossible/Cordova-DocPicker#13]
You get an error the first time you run the plugin, and the doc picker is very slow to open:

`Main Thread Checker: UI API called on a background thread: -[UIDocumentPickerViewController initWithDocumentTypes:inMode:]`

Xcode shows error:
`UIDocumentPickerViewController.delegate must be used from main thread only`
on DocumentPicker.swift line 48:
`picker.delegate = self`

**Comment by AmadeuReal** [comment]
Thanks for opening this issue. Fixed on the last release 1.2.2
