### ISSUE TITLE
Invalid callback id received by sendPluginResult

### ISSUE THREAD

**Issue by cikcoh** [iampossible/Cordova-DocPicker#4]
This plugin used to work util i tested it today..
i get runtime error shows on xcode output console. 

> Invalid callback id received by sendPluginResult 

Then i tried removing and adding plugin again >cordova build
get error:

>         'DocumentPickerOriginal' is not assignable to type 'Provider'. Type 'DocumentPickerOriginal' is not 
>             assignable to type 'ClassProvider'. Property 'provide' is missing in type 'DocumentPickerOriginal'.

**Comment by AmadeuReal** [comment]
Can you please provide more information about your environment?

**Comment by AmadeuReal** [comment]
Hi @cikcoh!

Can you please give more information about your issue? Otherwise I will have to close it.

Cheers.
