### ISSUE TITLE
Can't generate buid after add this plugin

### ISSUE THREAD

**Issue by bhavin00** [iampossible/Cordova-DocPicker#5]
Can't generate buid after add this plugin

**Comment by AmadeuReal** [comment]
Can you give more detail please?

**Comment by Comeonzs** [comment]
me too, said the error:The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targ, but i change swift Language Version,then did not running

**Comment by AmadeuReal** [comment]
Hi guys!

Sorry for taking so long to get back to you. Can you please remove the plugin and add it again?
You can remove it by: `cordova plugin rm cordova-plugin-documentpicker`
Followed by: `cordova plugin add https://github.com/iampossible/Cordova-DocPicker.git`
